openapi: 3.0.0
info:
  title: REST API for a blog
  version: 1.0.0
servers:
  - url: https://blog-api-production-3e1e.up.railway.app/api
    description: Production server
  - url: http://localhost:3000/api
    description: Development server
